annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/mcp-prometheus/issues\n"
chartApiVersion: v2
chartFile: mcp-prometheus-0.8.2.tgz
dateCreated: '2026-09-05T11:02:56.711943Z'
digest: 6e13ab41d0920957e2f6484bda7ec6d82d9e3a38485493da0843dbafa392dea9
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
