annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.1.61.tgz
dateCreated: '2026-05-20T19:15:09.997765Z'
digest: 3044a4769d5515770d439a8a45db14fb9b13744bf21292054bc0c843c20ce252
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
