annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.42.tgz
dateCreated: '2026-03-16T11:46:11.279204Z'
digest: c0cd451425dfb876af26214155b4911c35122c22b3ccfa336eaf262340ea02f7
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
