annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-catalog/kube-prometheus-stack-13.0.1.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-catalog/kube-prometheus-stack-13.0.1.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-catalog/kube-prometheus-stack-13.0.1.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-13.0.1.tgz
dateCreated: '2024-11-18T08:55:36.690605Z'
digest: 212b553521b9bdaff46899e6fa1af579e4e4cf830188ce69b41a9dedb239ba10
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
