annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.1.64.tgz
dateCreated: '2026-05-26T07:20:54.806420Z'
digest: 691b01ea24e478cf6dcf022b4fbf8f27c7afd136c3129f76982d44e1824796a3
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
