annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.2.21.tgz
dateCreated: '2026-06-20T12:01:47.071605Z'
digest: effbb07881aa4dd638bd5a1b872d4f2141735da45689660f438817786668f3d2
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
