annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.1.87.tgz
dateCreated: '2026-06-03T12:34:53.764098Z'
digest: 3026211a6dfafe3d9ed128b63eeb68b277f42eca5708cd6783f4099c32b1faba
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
