annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.45.tgz
dateCreated: '2026-03-17T13:19:02.817607Z'
digest: 222255e35b897eef0f2ab80c6c9b277f4fa28cffb2b228dfcc228637c4e67908
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
