annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.57.tgz
dateCreated: '2026-03-25T08:28:19.399631Z'
digest: 925bcc32ad9a1eeabd226f3db1dbd6312601b5cd1f4327630a26085737e121e8
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
