annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-catalog/prometheus-operator-app-4.2.3.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-catalog/prometheus-operator-app-4.2.3.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-catalog/prometheus-operator-app-4.2.3.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-operator-app-4.2.3.tgz
dateCreated: '2023-04-25T15:57:33.551860'
digest: 1903c2712834b4f076049531a28c0c7acbc987f70b9dcb8bd7817afbd0dfcbc5
home: https://github.com/giantswarm/prometheus-operator-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
