annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.1.72.tgz
dateCreated: '2026-05-28T15:53:07.771464Z'
digest: 685af1af18c3844e7a71760a91c0ba9853b260f055eb6c982a287fd66d5be567
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
