annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.1.88.tgz
dateCreated: '2026-06-04T08:24:15.318463Z'
digest: 102a99931b65a50e80d6290854e53bae10a7cabca371247fd756bc16a1436483
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
