annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.1.6.tgz
dateCreated: '2026-04-09T11:20:05.966222Z'
digest: 3798aeaf58891ffc37338a82461416bcccfffdcf99a0a360ddb8209a7e04d5dc
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
