annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/mcp-prometheus/issues\n"
chartApiVersion: v2
chartFile: mcp-prometheus-0.8.3.tgz
dateCreated: '2026-09-05T13:38:10.275574Z'
digest: cad2f2a897cd0373a05385a23815dc6defd3b0e6123d41e646b492db6592b19d
home: https://github.com/giantswarm/mcp-prometheus
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
